import type { LayoutServerLoad } from './$types';
import { categoriesQuery, type Category } from '$lib/sanity/queries';
import { BYPASS_TOKEN } from '$env/static/private';

export const config = {
	isr: {
		// Expiration time (in seconds) before the cached asset will be re-generated by invoking the Serverless Function.
		// Setting the value to `false` means it will never expire.
		expiration: 86400,

		// Random token that can be provided in the URL to bypass the cached version of the asset, by requesting the asset
		// with a __prerender_bypass=<token> cookie.
		//
		// Making a `GET` or `HEAD` request with `x-prerender-revalidate: <token>` will force the asset to be re-validated.
		bypassToken: BYPASS_TOKEN,

		// List of valid query parameters. Other parameters (such as utm tracking codes) will be ignored,
		// ensuring that they do not result in content being regenerated unnecessarily
		allowQuery: ['status', 'category']
	}
};

export const load: LayoutServerLoad = async ({ params, locals }) => {
	const { preview, loadQuery } = locals;
	const { slug } = params;

	const initial = await loadQuery<Category[]>(
		categoriesQuery,
		{ slug },
		{
			useCdn: false
		}
	);

	// console.log(initial);

	return {
		categories: {
			query: categoriesQuery,
			params: { slug },
			options: { initial }
		},
		preview
	};
};
